version: '3.9'
services:
  wordpress-cli:
    image: wordpress:cli
    tty: true
    restart: always
    volumes:
      - ./public_html:/var/www/html
    working_dir: /var/www/html
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: password
    profiles:
      - cli
  wordpress:
    image: wordpress
    volumes:
      - ./public_html:/var/www/html
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: password
    depends_on:
      - db
  db:
    image: mysql:8
    restart: always
    volumes:
      - db-store:/var/lib/mysql
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: password
    ports:
      - "63306:3306"
volumes:
  db-store: